--     _   __                    _
--    / | / /___   ____  _   __ (_)____ ___
--   /  |/ // _ \ / __ \| | / // // __ `__ \
--  / /|  //  __// /_/ /| |/ // // / / / / /
-- /_/ |_/ \___/ \____/ |___//_//_/ /_/ /_/
--

require "core.autocommands"
require "core.options"
require "core.plugins"
require "plugins.notify"
require "core.colorscheme"
require "core.luasnip"
require "core.cmp"
require "core.lsp"
require "core.treesitter"
require "core.usercommands"
require "plugins.alpha"
require "plugins.autopairs"
require "plugins.better-escape"
require "plugins.colorizer"
require "plugins.comment"
require "plugins.comment-frame"
require "plugins.conform"
require "plugins.crates"
require "plugins.diffview"
require "plugins.dressing"
require "plugins.flutter-tools"
require "plugins.gitsigns"
require "plugins.illuminate"
require "plugins.indentline"
require "plugins.log-highlight"
require "plugins.lsp-progress"
require "plugins.lualine"
require "plugins.neo-tree"
require "plugins.nomodoro"
require "plugins.numb"
require "plugins.project"
require "plugins.sg"
require "plugins.telescope"
require "plugins.todo-comments"
require "plugins.toggleterm"
require "plugins.treesitter-context"
require "plugins.virt-column"
require "plugins.whichkey"
