models:
  'qwen-3.5-2B':
    proxy: 'http://127.0.0.1:8012'
    name: 'Qwen 3.5 2B'
    cmd: |
      /opt/homebrew/bin/llama-server
      --host 127.0.0.1
      --port 8012
      -hf unsloth/Qwen3.5-2B-GGUF:UD-Q4_K_XL
      --ctx-size 0
      --temp 1.0
      --min-p 0.0
      --top-p 0.95
      --top-k 20
      --repeat-penalty 1.0
      --presence-penalty 0.0
      --jinja
      --parallel 1
  'qwen-3.5-4B-Instruct':
    proxy: 'http://127.0.0.1:8012'
    name: 'Qwen 3.5 4B'
    cmd: |
      /opt/homebrew/bin/llama-server
      --host 127.0.0.1
      --port 8012
      -hf unsloth/Qwen3.5-4B-GGUF:UD-Q4_K_XL
      --ctx-size 0
      --temp 1.0
      --min-p 0.0
      --top-p 0.95
      --top-k 20
      --repeat-penalty 1.0
      --presence-penalty 0.0
      --jinja
      --parallel 1
  'qwen-3.5-4B-Thinking':
    proxy: 'http://127.0.0.1:8012'
    name: 'Qwen 3.5 4B'
    cmd: |
      /opt/homebrew/bin/llama-server
      --host 127.0.0.1
      --port 8012
      -hf unsloth/Qwen3.5-4B-GGUF:UD-Q4_K_XL
      --ctx-size 0
      --temp 1.0
      --min-p 0.0
      --top-p 0.95
      --top-k 20
      --repeat-penalty 1.0
      --presence-penalty 0.0
      --chat-template-kwargs '{"enable_thinking":true}'
      --jinja
      --parallel 1
  'qwen-2.5-coder-1.5B-Instruct-128K-Q6':
    proxy: 'http://127.0.0.1:8012'
    name: 'Qwen 2.5 Coder 1.5B (128K)'
    ttl: 300
    cmd: |
      /opt/homebrew/bin/llama-server
      --host 127.0.0.1
      --port 8012
      -hf unsloth/Qwen2.5-Coder-1.5B-Instruct-128K-GGUF:Q6_K
      --temp 0.7 
      --min-p 0.0 
      --top-p 0.8 
      --top-k 20 
      --repeat-penalty 1.05
      --jinja
      --parallel 1
  'gemma-4-e2b':
    proxy: 'http://127.0.0.1:8012'
    name: 'Gemma 4 E2B'
    cmd: |
      /opt/homebrew/bin/llama-server
      --host 127.0.0.1
      --port 8012
      -hf unsloth/gemma-4-E2B-it-GGUF:UD-Q4_K_XL
      --temp 1.0 
      --top-p 0.95 
      --top-k 64 
      --jinja
      --parallel 1
  'gemma-4-e4b':
    proxy: 'http://127.0.0.1:8012'
    name: 'Gemma 4 E4B'
    cmd: |
      /opt/homebrew/bin/llama-server
      --host 127.0.0.1
      --port 8012
      -hf unsloth/gemma-4-E4B-it-GGUF:UD-Q4_K_XL
      --temp 1.0 
      --top-p 0.95 
      --top-k 64 
      --jinja
      --parallel 1
  'whisper':
    proxy: 'http://127.0.0.1:9090'
    checkEndpoint: /v1/audio/transcriptions/
    cmd: |
      /opt/homebrew/bin/whisper-server
      --host 127.0.0.1
      --port 9090
      --flash-attn
      --request-path /v1/audio/transcriptions --inference-path ""
