return {
  kind_icons = {
    Text = " ",
    Method = " ",
    Function = "󰊕 ",
    Constructor = " ",
    Field = " ",
    Variable = " ",
    Class = " ",
    Interface = " ",
    Module = " ",
    Property = " ",
    Unit = " ",
    Value = " ",
    Enum = " ",
    Keyword = " ",
    Snippet = " ",
    Color = " ",
    File = " ",
    Reference = " ",
    Folder = " ",
    EnumMember = " ",
    Constant = " ",
    Struct = " ",
    Event = " ",
    Operator = " ",
    TypeParameter = " ",
  },
  file = " ",
  find = " ",
  folder = " ",
  configuration = " ",
  lazy = "󰒲 ",
  quit = " ",
  gitsigns = {
    add = "▎",
    change = "▎",
    delete = "󰐊",
    topdelete = "󰐊",
    changedelete = "▎",
    untracked = "┆",
  },
  indent_line = "▏",
  virt_line = "┆",
  mode = "",
  branch = "󰊢",
  progress = "󰦪",
  added = " ",
  modified = " ",
  removed = " ",
  renamed = " ",
  ignored = " ",
  unstaged = " ",
  staged = " ",
  conflict = " ",
  untracked = " ",
  error = " ",
  warn = " ",
  info = " ",
  hint = "󰌵 ",
  debug = " ",
  trace = " ",
  readonly = "",
  package_installed = " ",
  package_pending = " ",
  package_uninstalled = " ",
  folder_filled = "",
  selection_caret = " ",
  separator = "",
  bot = " ",
  person = " ",
  copilot = " ",
  copilot_disabled = " ",
  smiley = " ",
  codecompanion = {
    buffer_pin = " ",
    buffer_watch = " ",
    chat_context = " ",
    chat_fold = " ",
    tool_pending = " ",
    tool_in_progress = " ",
    tool_failure = " ",
    tool_success = " ",
  },
  spinners = {
    "⠋",
    "⠙",
    "⠹",
    "⠸",
    "⠼",
    "⠴",
    "⠦",
    "⠧",
    "⠇",
    "⠏",
  },
}
