[helpers]

[bin.files]
"local/bin" = "~/.local/bin/"

[fish.files]
"config/fish" = "~/.config/fish"

[lazygit.files]
"config/lazygit" = "~/.config/lazygit"

[nvim.files]
"config/nvim" = "~/.config/nvim"

[wezterm.files]
"config/wezterm" = "~/.config/wezterm"
