[helpers]

[bin.files]
"local/bin" = "~/.local/bin/"

[fish.files]
"config/fish" = "~/.config/fish"

[lazygit.files]
"config/lazygit" = "~/.config/lazygit"

[nvim.files]
"config/nvim" = "~/.config/nvim"

[wezterm.files]
"config/wezterm" = "~/.config/wezterm"

[zed.files]
"config/zed" = "~/.config/zed"

[ghostty.files]
"config/ghostty" = "~/.config/ghostty"

[fastfetch.files]
"config/fastfetch" = "~/.config/fastfetch"

[opencode.files]
"config/opencode" = "~/.config/opencode"

[llama-swap.files]
"config/llama-swap" = "~/.config/llama-swap"
